### PR TITLE
Strip trailing slash from server URL

### LINKED ISSUE #2: Should not care if server URL has a trailing `/`
The readme, and the in app form ask for the Go server URL.
If you enter URL including the terminating Slash, 
then there are no issues until you attempt to log-in.
Then you get a redirected to 404 page.

I would not say that it is entirely correct or incorrect to consider the URL to have a `/`.
In general entering either with or without the `/` in a web-browser works.
So I think either should be valid in either  form.

## Steps to reproduce

1 . Login to GoCD Server as admin and navigate to Admin > Security > Authorization Configuration
2 . Click on Add to create new authorization configuration:
3. Specify id for auth config, e.g. "guest_auth
4. Select Guest Login Plugin for Plugin Id
5. **Specify Go Server Url, with a slash on the end. Eg. https://<GO_SERVER_URL>/go/**
6. Specify Username of the guest user.
7. Specify Display name of the guest user.
8.  Click "check connection" and note that it passes successfuly
9. Attempt to log in, by clicking `Guest`
10. Be redirected to an 404 error page. as there is an extra / in the url. e.g.: `https://<GO_SERVER_URL>/go//plugin/cd.go.contrib.authorization.guest/authenticate`

### PR DESCRIPTION
**Pull request by arunvelsriram**
Fixes #2

### CODE REVIEW

**Comment by arvindsv** [comment]
Makes sense to me. Thanks, @arunvelsriram. Merging.

**Comment by arvindsv** [comment]
It's released in https://github.com/gocd-contrib/gocd-guest-login-plugin/releases/tag/v2.0.0-52-exp

I can remove from it being "Pre-release" if you can confirm it works ok.

**Comment by arunvelsriram** [comment]
It's not working. It needs to be compiled with Java 8 I guess. I faced the same issue when I tested locally before pushing the fix.

```
 Failed to load plugin: plugins_work/guest-login.jar. Plugin is invalid. Reasons [Class [cd.go.authorization.guest.GuestLoginPlugin] could not be loaded. Message: [cd/go/authorization/guest/GuestLoginPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0].
...
```

**Comment by arvindsv** [comment]
@arunvelsriram Oh, sorry. Didn't see.

Java 8 support is deprecated and will stop working soon (see https://www.gocd.org/2019/05/21/official-stance-on-java/). The pipeline that builds this is using a newer version, I think.

The command you provided works in GoCD 19.6.0:

```
docker run -p8153:8153 -p8154:8154 \
  -e GOCD_PLUGIN_INSTALL_guest-login=https://github.com/gocd-contrib/gocd-guest-login-plugin/releases/download/v2.0.0-52-exp/gocd-guest-login-plugin-2.0.0-52.jar \
  gocd/gocd-server:v19.6.0
```

I was able to set up the auth config to use the plugin. Do you think that's alright?

**Comment by arunvelsriram** [comment]
Looks good to me. 

Noticed a different issue with the given docker image `gocd/gocd-server:v19.6.0`: The container is not handling the signals properly so I couldn't stop the container by sending an interrupt.

**Comment by arvindsv** [comment]
Yes. I saw that too. @adityasood @GaneshSPatil - have you seen that?

**Comment by GaneshSPatil** [comment]
> Looks good to me.
> 
> Noticed a different issue with the given docker image `gocd/gocd-server:v19.6.0`: The container is not handling the signals properly so I couldn't stop the container by sending an interrupt.

@arunvelsriram -- A fix has been added to address this issue. And will be available as part of `v19.7.0` release of GoCD.

For `19.6.0` release, run the GoCD container with `-t, --tty` option.
Example: `docker container run -t gocd/gocd-server:v19.6.0`

**Pull request merged**
